FROM nginx:alpine

WORKDIR /root/temp

RUN apk update && \
    apk add --update git nodejs nodejs-npm 


RUN git clone https://github.com/BenjaminRochez/styleguider.git /opt/styleguider
RUN cd /opt/styleguider && npm install hugo 
RUN npm run hugo

RUN cp -r /opt/styleguider/public/* /usr/share/nginx/html